### ISSUE TITLE
nfd-dbg, ndn-cxx-dbg: debug symbols for nfd and ndn-cxx

### ISSUE THREAD

**Issue by yoursunny** [named-data/ppa-packaging#11]
Create a **ndn-cxx-dbg** package that contains debug symbols for ndn-cxx.
This would allow developers who link their projects with **ndn-cxx-dev** to debug their projects.

**Comment by cawka** [comment]
I have little knowledge on how to use -dbg oackages and even less knowledge on how to create them.  Can you provide documentation/examples for that?

**Comment by yoursunny** [comment]
I was suggested to install a few **-dbg** packages in [this thread](https://github.com/mate-desktop/pluma/issues/99#issuecomment-77679303). After that, `gdb` can produce a backtrace with function names and variables names.
I do not know how to create those packages, but the debug symbol files can be created by `objcopy --only-keep-debug` command.
