### ISSUE TITLE
Scripts license

### ISSUE THREAD

**Issue by pinepain** [named-data/ppa-packaging#14]
Hi, thanks for the wonderful scripts! It really saved me a lot of time.

I already using your scripts to build some of my projects. While I made some tiny modifications, I prefer to clarify whether I can use your scripts under MIT license? Can you also put some copyrights and license info in your work, please?

**Comment by cawka** [comment]
Dear Bogdan, thanks for pointing out the issue.  I added the license statement for Apache 2.0 license.
