### ISSUE TITLE
armhf architecture

### ISSUE THREAD

**Issue by yoursunny** [named-data/ppa-packaging#15]
`armhf` is a popular architecture for single board computers such as Raspberry Pi and C.H.I.P. Some flavors of Ubuntu (such as Lubuntu or Ubuntu MATE) are available for those computers. It would be nice to build NDN packages for `armhf` architecture.

**Comment by cawka** [comment]
Our build scripts are not ready for the architecture... There is some issue with paths for boost library detection (e.g., https://launchpadlibrarian.net/300569644/buildlog_ubuntu-xenial-armhf.ndn-cxx_0.5.0-27-g0669061a-ppa1~xenial_BUILDING.txt.gz)

Do you have a VM that can be used to debug and fix the problem?

**Comment by yoursunny** [comment]
The problem is in ndn-cxx build script which [hard-codes](https://github.com/named-data/ndn-cxx/blob/7d05427cc10dd3529ff6f709f75055d0cd3883a7/.waf-tools/boost.py#L57) the multiarch tuple to locate Boost libraries.
It should use [`dpkg-architecture -qDEB_HOST_MULTIARCH`](https://wiki.debian.org/Multiarch/Tuples#Supporting_interfaces) to determine this tuple.

**Comment by cawka** [comment]
c3d86082f15992e51bc3bfe4ac375db9e9b2033d and later include support for `arm64`, `armel`, `armhf`, and `ppc64el` architecture.  However, the package will not yet work on `armhf` (possibly others) due to bug [3935](https://redmine.named-data.net/issues/3935).
